## . ./.secrets
## pm2 start rules.json

export ZEOCHAT_PROTOCOL_HTTP=http
export ZEOCHAT_PROTOCOL_WS=ws
export ZEOCHAT_DOMAIN=localhost
export ZEOCHAT_BASE_HTTP=http://localhost:3000
export ZEOCHAT_PORT_PROXY=3000
export ZEOCHAT_PORT_SOCKET=3001
export ZEOCHAT_PORT_MONITOR=3002
export ZEOCHAT_PORT_MATCH=3003
export ZEOCHAT_PORT_WEB=3004
export ZEOCHAT_PORT_CLASSIFIER=3005
export ZEOCHAT_PORT_ADMINWEB=3006
export ZEOCHAT_DB_CONNECTION=mongodb://<EXAMPLE>:<EXAMPLE>@<EXAMPLE>.mlab.com:41720/zeochat-local
export ZEOCHAT_DB_NAME=zeochat-local
export ZEOCHAT_S3_BUCKET_ASSETS=zeochat-assets
export ZEOCHAT_S3_BUCKET_WEB=zeochat.com
export ZEOCHAT_S3_ACCESS=<EXAMPLE>
export ZEOCHAT_S3_SECRET=<EXAMPLE>

unset NOW_TOKEN
export NOW_TOKEN_WEB=<EXAMPLE>
export NOW_TOKEN_SOCKET=<EXAMPLE>
export NOW_TOKEN_MATCH=<EXAMPLE>
export NOW_TOKEN_MONITOR=<EXAMPLE>

export NOW_ZEOCHAT_PAPERTRAIL_HOST=<EXAMPLE>.papertrailapp.com
export NOW_ZEOCHAT_PAPERTRAIL_PORT=<EXAMPLE>

export ZEOCHAT_PAPERTRAIL_HOST=<EXAMPLE>.papertrailapp.com
export ZEOCHAT_PAPERTRAIL_PORT=<EXAMPLE>
export ZEOCHAT_PAPERTRAIL_APP=default app
unset ZEOCHAT_PAPERTRAIL_HOST
unset ZEOCHAT_PAPERTRAIL_PORT
unset ZEOCHAT_PAPERTRAIL_APP

now --token $NOW_TOKEN_SOCKET secrets add ZEOCHAT_DB_CONNECTION $ZEOCHAT_DB_CONNECTION
now --token $NOW_TOKEN_SOCKET secrets add ZEOCHAT_PAPERTRAIL_HOST $NOW_ZEOCHAT_PAPERTRAIL_HOST
now --token $NOW_TOKEN_SOCKET secrets add ZEOCHAT_PAPERTRAIL_PORT $NOW_ZEOCHAT_PAPERTRAIL_PORT

now --token $NOW_TOKEN_MONITOR secrets add ZEOCHAT_S3_ACCESS $ZEOCHAT_S3_ACCESS
now --token $NOW_TOKEN_MONITOR secrets add ZEOCHAT_S3_SECRET $ZEOCHAT_S3_SECRET
now --token $NOW_TOKEN_MONITOR secrets add ZEOCHAT_PAPERTRAIL_HOST $NOW_ZEOCHAT_PAPERTRAIL_HOST
now --token $NOW_TOKEN_MONITOR secrets add ZEOCHAT_PAPERTRAIL_PORT $NOW_ZEOCHAT_PAPERTRAIL_PORT

now --token $NOW_TOKEN_MATCH secrets add ZEOCHAT_DB_CONNECTION $ZEOCHAT_DB_CONNECTION
now --token $NOW_TOKEN_MATCH secrets add ZEOCHAT_S3_ACCESS $ZEOCHAT_S3_ACCESS
now --token $NOW_TOKEN_MATCH secrets add ZEOCHAT_S3_SECRET $ZEOCHAT_S3_SECRET
now --token $NOW_TOKEN_MATCH secrets add ZEOCHAT_PAPERTRAIL_HOST $NOW_ZEOCHAT_PAPERTRAIL_HOST
now --token $NOW_TOKEN_MATCH secrets add ZEOCHAT_PAPERTRAIL_PORT $NOW_ZEOCHAT_PAPERTRAIL_PORT

echo 'ZEOCHAT ENV VARS SET'